# settings-dev.yaml
name: "go-gin"
port: 8022
logsAddress: "./logs/"
debug: true

mysql:
  name: "root"
  host: "127.0.0.1"
  port: 3306
  password: "admin123"
  dbName: "test"

redis:
  addr: "localhost:6379"
  pwd: ""
  db: 0